### ISSUE TITLE
Amazing talk

### ISSUE THREAD

**Issue by FrankReh** [ThorstenHans/wasmio-2024-demos#2]
This is the YT link to the talk.

https://www.youtube.com/watch?v=NFbjQNqWi94

I had found it by searching for "WebAssembly Component Model". The video provides great food for thought. It's really well done and a lot of thought must have gone into it.

**Comment by ThorstenHans** [comment]
Thanks a lot for the feedback ❤️

**Comment by ThorstenHans** [comment]
Added the link to the README of the repo. Thanks once again @FrankReh
